FROM node:20.12.2-bookworm@sha256:3864be2201676a715cf240cfc17aec1d62459f92a7cbe7d32d1675e226e736c9 AS node

COPY src/scripts /scripts

WORKDIR /scripts

RUN npm install

CMD ["/scripts/docker-run.sh"]